id: testpackage-{VER}
meta:
  maintainer:
    name: Robert Yang, Harrison Li
    email: minghaoy@umich.edu, harrisonliding@gmail.com
gboxes: 
  - id: {GBOX}-{VER}
    meta:
      title: PanglaoDB data download
      subtitle: "Downloading data from PanglaoDB"
      description: ScRNA raw data store on PanglaoDB database can be accessed and downloaded here. If you want to perform analysis on that, please go to the PanglaoDB website (https://panglaodb.se/samples.html), find the raw sample data you want, and then record the SRA and SRS numbers to download the certain data to GranatumX. This Gbox will export them into assay for further analysis.
    endpoints:
      backend:
        type: docker
        image: {GBOX}
        cmd: Rscript ./main.R
    frontend:
      uploadedFiles:
        - label: PanglaoDB sample Rdata to upload
          injectInto: assayFile
          #     optional: true
          #args:
          #- type: text 
          #injectInto: SRA_num # this field is used to access arguments from the main script
          #default: SRA553822
          #label: NCBI SRA Submission Identifier (e.g. SRA553822)
          #- type: text
          #injectInto: SRS_num
          #default: SRS2119548
          #label: NCBI SRS Sample Identifier (e.g. SRS2119548)
          #  imports:
          #   - kind: assay # the "assay" data type by which GranatumX records genomic assays
    #      label: Assay
    #      injectInto: exampleImport # this field is used to access imports from the main script
      exports:
        - kind: assay # the "assay" data type is commonly used for both imports and exports through GranatumX
          extractFrom: PanglaoDB assay # this field is used to access exports from the main script
    #      meta: {}
